package Images;

public enum GameImages {
    BACKGROUND, SETTING, SOUND, GUIDE, PLAY, QUIT, PAUSE,
    GOLD, LIFE, WAVE, UPGRADE, DESTROY,
    WEEK_ENEMY, QUICK_ENEMY, NORMAL_ENEMY, TANK, PLANE, TANK_GUN,
    QUICK_TOWER_LV1, NORMAL_TOWER_LV1, SLOW_TOWER_LV1, QUICK_TOWER_LV2, NORMAL_TOWER_LV2, SLOW_TOWER_LV2,
    QUICK_TOWER_BULLET, NORMAL_TOWER_BULLET, SLOW_TOWER_BULLET,
    QUICK_TOWER_BULLET_EXPLOSION, NORMAL_TOWER_BULLET_EXPLOSION, SLOW_TOWER_BULLET_EXPLOSION;
}